languages = {
    'English': {
        'rotato'            : 'Rotato', 
        'language'          : 'Language', 
        'reload_webcam'     : 'Reload Webcam',
        'settings'          : 'Settings',
        'camera'            : 'Camera',
        'select_camera'     : 'Select Camera',
        'no_camera'         : 'No Cameras Found!',
        'save'              : 'Save',
        'help'              : 'Help',
        'brightness'        : 'Brightness',
        'time'              : 'Time',
        'seconds_short'     : 's',
        'start'             : 'Start',
        'stop'              : 'Stop',
        'reset'             : 'Reset',
        'save_data'         : 'Save Data',
        'save_plot'         : 'Save Plot',
        'saved_data_title'  : 'Data Saved!',
        'saved_plot_title'  : 'Graph Saved!',
        'saved_data'        : "Data saved! Check your 'downloads' folder for the csv file.",
        'saved_plot'        : "Graph saved! Check your 'downloads' folder for the graph image.",
        'time_span'         : 'Time Span',
        'ap_radius'         : 'Aperture Size',
        'brightness_lim'    : 'Brightness Limit',
        'filter'            : 'Filter',
        'clear'             : 'Clear',
        'red_short'         : 'R',
        'green_short'       : 'G',
        'blue_short'        : 'B',
        'mess_up_data'      : 'Mess Up Data',
        'noise'             : 'Noise',
        'add_noise'         : 'Add Noise?',
        'vary_interval'     : 'Vary Time?',
        'time_interval'     : 'Time Interval',
        'randomise_time'    : 'Randomise Time Interval',
        'gap_duration'      : 'Gap Duration',
        'gap_frequency'     : 'Gap Frequency',
        'add_gaps'          : 'Add Gaps?',
        },
    
    'Cymraeg': {
        'rotato'            : 'Rotato', 
        'language'          : 'Iaith', 
        'reload_webcam'     : "Ail-llwytho'r Gwe-gam",
        'settings'          : 'Gosodiadau',
        'camera'            : 'Camera',
        'select_camera'     : 'Dewis Camera',
        'no_camera'         : 'Dim Camera wedi Cysylltu!',
        'save'              : 'Cadw',
        'help'              : 'Cymorth',
        'brightness'        : 'Disgleirdeb',
        'time'              : 'Amser',
        'seconds_short'     : 'eil',
        'start'             : 'Dechrau',
        'stop'              : 'Stop',
        'reset'             : 'Ailosod',
        'save_data'         : 'Safio Data',
        'save_plot'         : 'Safio Graff',
        'saved_data_title'  : 'Data wedi Safio!',
        'saved_plot_title'  : 'Graff wedi Safio!',
        'saved_data'        : "Data wedi safio! Gwelwch eich ffolder 'lawrlwythiadau' ar gyfer y ffeil csv.",
        'saved_plot'        : "Graff wedi safio! Gwelwch eich ffolder 'lawrlwythiadau' ar gyfer llun y graff.",
        'time_span'         : 'Cyfnod Amser',
        'ap_radius'         : 'Maint Cylch',
        'brightness_lim'    : 'Ffinau Ddisgleirdeb',
        'filter'            : 'Ffilter',
        'clear'             : 'Clîr',
        'red_short'         : 'R',
        'green_short'       : 'G',
        'blue_short'        : 'B',
        'mess_up_data'      : "Gwneud Llanast o'r Data",
        'noise'             : 'Sŵn',
        'add_noise'         : 'Ychwanegu Sŵn?',
        'vary_interval'     : 'Amrywio Amser?',
        'time_interval'     : 'Cyfnod Amser',
        'randomise_time'    : 'Amrywio Cyfnod Amser',
        'gap_duration'      : 'Hyd Bylchau',
        'gap_frequency'     : 'Amlder Bylchau',
        'add_gaps'          : 'Ychwanegu Bylchau?',
        }
    }   



languges_base = {
    'LANGUAGE': {
        'rotato'            : '', 
        'language'          : '', 
        'reload_webcam'     : '',
        'settings'          : '',
        'camera'            : '',
        'select_camera'     : '',
        'no_camera'         : '',
        'save'              : '',
        'help'              : '',
        'brightness'        : '',
        'time'              : '',
        'seconds_short'     : '',
        'start'             : '',
        'stop'              : '',
        'reset'             : '',
        'save_data'         : '',
        'save_plot'         : '',
        'saved_data_title'  : '',
        'saved_plot_title'  : '',
        'saved_data'        : '',
        'saved_plot'        : '',
        'time_span'         : '',
        'ap_radius'         : '',
        'brightness_lim'    : '',
        'filter'            : '',
        'clear'             : '',
        'red_short'         : '',
        'green_short'       : '',
        'blue_short'        : '',
        'mess_up_data'      : '',
        'noise'             : '',
        'add_noise'         : '',
        'vary_interval'     : '',
        'time_interval'     : '',
        'randomise_time'    : '',
        'gap_duration'      : '',
        'gap_frequency'     : '',
        'add_gaps'          : '',
        ''                  : '',
        ''                  : '',
        ''                  : '',
        ''                  : '',
        ''                  : '',
        ''                  : '',
        ''                  : '',
        ''                  : '',
        ''                  : '',
        ''                  : '',
        ''                  : '',
        ''                  : '',
        }
    }
