languages = {
    'English': {
        'rotato'            : 'Rotato', 
        'language'          : 'Language', 
        'settings'          : 'Settings',
        'camera'            : 'Camera',
        'select_camera'     : 'Select Camera',
        'no_camera'         : 'No Cameras Found!',
        'save'              : 'Save',
        'help'              : 'Help',
        'brightness'        : 'Brightness',
        'time'              : 'Time',
        'seconds_short'     : 's',
        'start'             : 'Start',
        'stop'              : 'Stop',
        'reset'             : 'Reset',
        'save_data'         : 'Save Data',
        'save_plot'         : 'Save Plot',
        'time_span'         : 'Time Span',
        'ap_radius'         : 'Aperture Size',
        'brightness_lim'    : 'Brightness Limit',
        'filter'            : 'Filter',
        'clear'             : 'Clear',
        'red_short'         : 'R',
        'green_short'       : 'G',
        'blue_short'        : 'B',
        'mess_up_data'      : 'Mess Up Data',
        },
    
    'Cymraeg': {
        'rotato'            : 'Rotato', 
        'language'          : 'Iaith', 
        'settings'          : 'Gosodiadau',
        'camera'            : 'Camera',
        'select_camera'     : 'Dewis Camera',
        'no_camera'         : 'Dim Camera wedi Cysylltu!',
        'save'              : 'Cadw',
        'help'              : 'Cymorth',
        'brightness'        : 'Disgleirdeb',
        'time'              : 'Amser',
        'seconds_short'     : 'eil',
        'start'             : 'Dechrau',
        'stop'              : 'Stop',
        'reset'             : 'Ailosod',
        'save_data'         : 'Safio Data',
        'save_plot'         : 'Safio Graff',
        'time_span'         : 'Cyfnod Amser',
        'ap_radius'         : 'Maint Cylch',
        'brightness_lim'    : 'Ffinau Ddisgleirdeb',
        'filter'            : 'Ffilter',
        'clear'             : 'Clîr',
        'red_short'         : 'R',
        'green_short'       : 'G',
        'blue_short'        : 'B',
        'mess_up_data'      : "Gwneud Llanast o'r Data",
        }
    }   



languges_base = {
    'LANGUAGE': {
        'rotato'            : '', 
        'language'          : '', 
        'settings'          : '',
        'camera'            : '',
        'select_camera'     : '',
        'no_camera'         : '',
        'save'              : '',
        'help'              : '',
        'brightness'        : '',
        'time'              : '',
        'seconds_short'     : '',
        'start'             : '',
        'stop'              : '',
        'reset'             : '',
        'save_data'         : '',
        'save_plot'         : '',
        'time_span'         : '',
        'ap_radius'         : '',
        'brightness_lim'    : '',
        'filter'            : '',
        'clear'             : '',
        'red_short'         : '',
        'green_short'       : '',
        'blue_short'        : '',
        'mess_up_data'      : '',
        ''                  : '',
        ''                  : '',
        ''                  : '',
        ''                  : '',
        ''                  : '',
        ''                  : '',
        ''                  : '',
        ''                  : '',
        }
    }
